version: '3'
services:
  api-service:
    image: your-api-image
    container_name: api-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - backend

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
